micronaut:
  server:
    port: 8080
  application:
    name: mn-data-pg

jackson:
  bean-introspection-module: true

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'sa'
    dialect: POSTGRES

---
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: validate
        show_sql: false

flyway:
  datasources:
    default:
      locations: classpath:db/migration

---
micronaut:
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: "${JWT_GENERATOR_REFRESH_SECRET:eefe82f8-7ca6-11ea-bc55-0242ac130003}"
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:eefe82f8-7ca6-11ea-bc55-0242ac130003}"
